# SPDX-FileCopyrightText: Copyright 2026 run0edit authors (https://github.com/HastD/run0edit)
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Linters

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    name: REUSE spec compliance
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check REUSE compliance
        shell: bash
        run: |
          pipx run reuse lint

  rpmlint:
    name: Lint RPM spec
    runs-on: ubuntu-26.04
    container: fedora:44 # zizmor: ignore[unpinned-images]
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          sudo dnf install -y rpmlint

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run rpmlint
        shell: bash
        run: |
          rpmlint rpm/run0edit.spec
