# SPDX-FileCopyrightText: (c) 2025-2026 run0edit authors <https://github.com/HastD/run0edit>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Python tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    name: Run Python unit tests and linters
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install coverage meson ruff ty
          sudo apt install just pandoc

      - name: Run tests
        run: |
          just test

  integration-test:
    name: Run integration tests
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install meson
          sudo apt install pandoc

      - name: Set up passwordless authentication
        run: |
          cat <<EOF | sudo tee /etc/polkit-1/rules.d/10-systemd-nopasswd.rules >/dev/null
          polkit.addRule(function(action, subject) {
              if (subject.user === "${USER}") {
                  return polkit.Result.YES;
              }
          });
          EOF

      - name: Run integration tests
        run: |
          mkdir -p build
          meson setup build -Dprefix=/usr -Dunit-tests=disabled -Dintegration-tests=enabled
          meson compile -C build
          meson test -C build --verbose integration-test
